assignment3 : main.o Manage.o Node.o AdjacentList.o Dijkstra.o
	g++ -o assignment3 main.o Manage.o Node.o AdjacentList.o Dijkstra.o
main.o:main.cpp
	g++ -c main.cpp
Manage.o:Manage.cpp Manage.h
	g++ -c Manage.cpp
Node.o:Node.cpp Node.h
	g++ -c Node.cpp
AdjacentList.o:AdjacentList.cpp AdjacentList.h
	g++ -c AdjacentList.cpp
Dijkstra.o:Dijkstra.cpp Dijkstra.h
	g++ -c Dijkstra.cpp
